# Generated by Django 4.2.23 on 2025-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_ext',
            new_name='choice_text',
        ),
    ]
